# Generated by Django 3.2.16 on 2026-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('department', models.CharField(choices=[('legal', 'Юридический'), ('technical', 'Технический'), ('accounting', 'Делопроизводство')], max_length=20, verbose_name='Отдел')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежки')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'db_table': 'register_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('organization', models.CharField(max_length=200, verbose_name='Организация')),
                ('department', models.CharField(choices=[('legal', 'Юридический'), ('technical', 'Технический'), ('accounting', 'Делопроизводство')], max_length=20, verbose_name='Отдел')),
                ('payment_doc', models.CharField(blank=True, max_length=100, verbose_name='№ платежного листа')),
                ('request_text', models.TextField(verbose_name='Текст заявки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('in_progress', 'Принята в работу'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('employee_response', models.TextField(blank=True, verbose_name='Ответ сотрудника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'db_table': 'service_request',
                'managed': True,
            },
        ),
    ]
