# Generated by Django 5.1.1 on 2026-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_auto_20260225_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterModelTable(
            name='registeruser',
            table='Register_Users',
        ),
    ]
